apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: demo
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
