apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      name: todo-app
      namespace: todo-app
      labels:
        app: todo-app
    spec:
      containers:
        - name: "todo-app"
          image: "hikhvar/todo-app-web:v1"
          command: ["./todo-app"]
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: todo-cache
                  key: endpoint
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 3000
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
